// We'll use react-icons instead of heroicons
// This file re-exports react-icons equivalents

export { 
  HiSearch as MagnifyingGlassIcon,
  HiShoppingBag as ShoppingBagIcon,
  HiHeart as HeartIcon,
  HiUser as UserIcon,
  HiSun as SunIcon,
  HiMoon as MoonIcon,
  HiMenu as Bars3Icon,
  HiX as XMarkIcon,
  HiChevronDown as ChevronDownIcon,
  HiChevronRight as ChevronRightIcon,
  HiChevronLeft as ChevronLeftIcon,
  HiArrowRight as ArrowRightIcon,
  HiArrowLeft as ArrowLeftIcon,
  HiPlus as PlusIcon,
  HiMinus as MinusIcon,
  HiTrash as TrashIcon,
  HiPencil as PencilIcon,
  HiEye as EyeIcon,
  HiStar as StarIcon,
  HiCheck as CheckIcon,
  HiX as XMarkIconSolid,
  HiLocationMarker as MapPinIcon,
  HiPhone as PhoneIcon,
  HiMail as EnvelopeIcon,
  HiShieldCheck as ShieldCheckIcon,
  HiTruck as TruckIcon,
  HiRefresh as ArrowPathIcon,
  HiClock as ClockIcon,
  HiExclamation as ExclamationTriangleIcon,
  HiInformationCircle as InformationCircleIcon,
  HiDocumentText as DocumentTextIcon,
  HiFilter as FunnelIcon,
  HiAdjustments as AdjustmentsHorizontalIcon,
  HiSortAscending as BarsArrowUpIcon
} from 'react-icons/hi';
